### ISSUE TITLE
unsafe command in install.sh

### ISSUE THREAD

**Issue by RealMrCactus** [materialgram/arch#1]
pacman -Sy should be replaced with pacman -Syu as the user could be unaware of this and possibly break their kernel on a distro that is rolling release and not having the latest software after a mirror update

**Comment by omansh-krishn** [comment]
I think you are actually thinking the opposite,
Also, `y` is needed because a new pkg repo is added, whose database needs to be downloaded

(correct me if you think I didn't understand your question)

**Comment by RealMrCactus** [comment]
> I think you are actually thinking the opposite, Also, `y` is needed because a new pkg repo is added, whose database needs to be downloaded
> 
> (correct me if you think I didn't understand your question)

You cannot run partial upgrades, they are unsupported/unrecommended go look at the Arch wiki you'll see it, the reason is partial upgrades end up causing issues with deps so lets say Nvidia required the latest kernel and the user installed Nvidia guess what it's not gonna work You must Syu

**Comment by omansh-krishn** [comment]
ohh NVIDIA, I don't have it, so didn't thought about it.

So, OK then, I'll add `u`.

BE HAPPY
